# Generated by Django 2.1 on 2021-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210603_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
